# Generated by Django 5.0.4 on 2024-04-19 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='profile_pick',
            new_name='profile_pics',
        ),
    ]
